### ISSUE TITLE
testsuite fails with libvirt >= 10.1.0

### ISSUE THREAD

**Issue by rnalrd** [virt-manager/virt-manager#648]
```
============================================================ test session starts =============================================================
platform linux -- Python 3.11.8, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/rnalrd/alpine_build/aports/community/virt-manager/src/virt-manager-4.1.0
configfile: setup.cfg
testpaths: tests/
collected 543 items / 5 deselected / 538 selected                                                                                            

[...]

========================================================== short test summary info ===========================================================
FAILED tests/test_nodedev.py::testDASDMdev - AssertionError: assert None == 'vfio_ccw-io'
FAILED tests/test_nodedev.py::testAPQNMdev - AssertionError: assert None == 'vfio_ap-passthrough'
FAILED tests/test_nodedev.py::testPCIMdev - AssertionError: assert None == 'nvidia-11'
FAILED tests/test_nodedev.py::testPCIMdevNewFormat - AssertionError: assert None == 'nvidia-11'
FAILED tests/test_cli.py::testCLI0001virt_install_many_devices - AssertionError: Command was: ./virt-install --connect __virtinst_test__test:///home/larena/alpine_build/aports/community/virt-manager/src...
FAILED tests/test_cli.py::testCLI0261virt_xml - AssertionError: Command was: ./virt-xml  test-for-virtxml --add-device --host-device 0x04b3:0x4485 --update --confirm --debug --connect _...
FAILED tests/test_cli.py::testCLI0284virt_xml_edit_cpu_host_copy - AssertionError: Conversion outputs did not match.
FAILED tests/test_cli.py::testCLI0366virt_xml_add_hostdev_mdev - AssertionError: Command was: ./virt-xml test-for-virtxml --print-diff --define --add-device --hostdev mdev_8e37ee90_2b51_45e3_9b25_bf8283...
FAILED tests/test_cli.py::testCLI0374virt_xml_add_hostdev_mdev_start - AssertionError: Command was: ./virt-xml test-state-shutoff --print-diff --start --add-device --hostdev mdev_8e37ee90_2b51_45e3_9b25_bf828...
========================================== 9 failed, 512 passed, 17 skipped, 5 deselected in 23.63s ==========================================
```

**Distro**: Alpine Edge
virt-manager v4.1.0

I have no problem with Alpine 3.19 that has pytest 7.4.3

**Comment by ptoscano** [comment]
What's the version of libvirt? I think those failures are the ones I saw after running the test suite against the newly released libvirt 10.1.0.

**Comment by phrdina** [comment]
All the mdev related errors are due to libvirt having not complete implementation of the test driver that is used by virt-manager test suite. So we basically need to skip these tests for now as they will always fail until libvirt is fixed.

The `virt_xml_edit_cpu_host_copy` could be fixed in virt-manager.

There seems to be one more failed test case as last time I run pytest I had only 8 failed tests.

**Comment by rnalrd** [comment]
> What's the version of libvirt? I think those failures are the ones I saw after running the test suite against the newly released libvirt 10.1.0.

Yes, 10.1.0

**Comment by Fantu** [comment]
Seems the same of fail to build on Debian: https://salsa.debian.org/libvirt-team/virt-manager/-/jobs/5481841
Contrary to other previous problems I don't see fix commit in git, or am I wrong? (I just gave a quick look)

**Comment by crobinso** [comment]
The CPU model test is fixed in git. I have patches for libvirt that fix the mdev bits

**Comment by Fantu** [comment]
Thanks, your virt-manager patches were applied in Debian (for now only in git), but there is still an error:
`ERROR    Error: --hostdev mdev_8e37ee90_2b51_45e3_9b25_bf8283c03110: Don't know how to generate nodedev for mdev type id 'None'`
https://salsa.debian.org/libvirt-team/virt-manager/-/jobs/5560563

**Comment by phrdina** [comment]
Yes, that is expected error as that was not fixed so far. In virt-manager we need to add version check to figure out if we need to skip that test or not and at the same time test driver in libvirt needs to be fixed to figure out the version of libvirt we need to check for in virt-manager. Patches were posted to libvirt mailing list so the work is in progress.

**Comment by jradxl** [comment]
I have these test-suite errors in test_cli.py on Ubuntu Jammy
when building everything from Sources
with Virt-Manager 4.1.0
and Libvirt 10.3.0
Is this the same issue as reported above?

```
=========================== short test summary info ============================
FAILED tests/test_cli.py::testCLI0057virt_install_osinfo_url - AssertionError...
FAILED tests/test_cli.py::testCLI0079virt_install_osinfo_url_with_disk - Asse...
FAILED tests/test_cli.py::testCLI0094virt_install_cloud_init_default - Assert...
FAILED tests/test_cli.py::testCLI0095virt_install_cloud_init_options1 - Asser...
FAILED tests/test_cli.py::testCLI0096virt_install_cloud_init_options2 - Asser...
FAILED tests/test_cli.py::testCLI0097virt_install_cloud_init_options3 - Asser...
FAILED tests/test_cli.py::testCLI0098virt_install_cloud_init_options4 - Asser...
FAILED tests/test_cli.py::testCLI0099virt_install_cloud_init_options5 - Asser...
FAILED tests/test_cli.py::testCLI0110virt_install_reinstall_cdrom - Assertion...
FAILED tests/test_cli.py::testCLI0114virt_install_osinfo_url_unattended - Ass...
FAILED tests/test_cli.py::testCLI0115virt_install_osinfo_unattended_treeapis
FAILED tests/test_cli.py::testCLI0116virt_install_osinfo_win7_unattended - As...
FAILED tests/test_cli.py::testCLI0117virt_install_osinfo_netinst_unattended
FAILED tests/test_cli.py::testCLI0119virt_install_unattended_remote_cdrom - A...
FAILED tests/test_cli.py::testCLI0120virt_install - AssertionError: Command w...
FAILED tests/test_cli.py::testCLI0261virt_xml - AssertionError: Command was: ...
FAILED tests/test_cli.py::testCLI0284virt_xml_edit_cpu_host_copy - AssertionE...
================== 17 failed, 507 passed, 19 skipped in 9.74s ==================

```

**Comment by phrdina** [comment]
Hi, thanks for the report. This is a new issue related to argcomplete. Need to investigate it why it suddenly stopped working.

**Comment by phrdina** [comment]
Did a bit of digging and it seems to be related to combination of old argcomplete and new python version. We will need to probably figure out a way how to detect that the installed argcomplete doesn't work correctly with installed python and skip these tests.

**Comment by phrdina** [comment]
Fixed by #672
