### ISSUE TITLE
Mouse pointer not visible inside the VM terminals

### ISSUE THREAD

**Issue by DanielP2D** [virt-manager/virt-manager#861]
Hi All, 
I am using Virtual Machine Viewer 7.0 on top of Ubuntu 22.04 LTS and used the following command to install the QEMU, 
sudo apt install -y qemu-system-x86 libvirt-daemon-system libvirt-clients virtinst bridge-utils virt-viewer git

As soon as I enter the VM terminal window, i lose the mouse pointer in my case using the laptops touchpac

Can anyone please tell me how to fix this issue?

**Comment by phrdina** [comment]
Hi, this issue tracker is for virt-manager, virt-viewer can be found here https://gitlab.com/virt-viewer/virt-viewer/ .

I don't know how to fix this issue but you can try using newer version to see if it is already fixed, version 7.0 is pretty old, the latest release is 11.0.

**Comment by DanielP2D** [comment]
Thank you for the quick response! 
I installed the Version 11 but its still the same issue, I directly get a terminal window and as soon as i move my cursor into it, the cursor disappears. This makes it very difficult for me to copy or paste any commands from my host system.
